linters:
  PropertySortOrder:
    order: smacss
  Indentation:
    width: 4
  ColorVariable:
    enabled: false
  EmptyLineBetweenBlocks:
    ignore_single_line_blocks: false
  MergeableSelector:
    force_nesting: false
  TransitionAll:
    enabled: true
  VendorPrefix:
    enabled: false
  Comment:
    enabled: false
  SelectorFormat:
    enabled: false
    # convention: snake_case
  IdSelector:
    enabled: false
  UrlFormat:
    enabled: false
